server:
  port: 88

spring:
  application:
    name:  cloud-consumerconsul-order
  cloud:
    consul:
      host: 192.168.0.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 192.168.0.165
        #port: 8006